import { RouterProvider, createRouter } from '@tanstack/react-router'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'

import '@/globals.css'

// Generated by TanStack Router Vite plugin from files in src/routes/
import { routeTree } from './routeTree.gen'

// Create the router instance with the generated route tree
const router = createRouter({ routeTree })

// Register the router for type-safe navigation throughout the app
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
)
