/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as App_routeRouteImport } from './routes/app/__route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects/$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app/projects/$projectId/index'
import { Route as AppProjectsProjectIdMembersRouteImport } from './routes/app/projects/$projectId/members'
import { Route as AppProjectsProjectIdKanbanRouteImport } from './routes/app/projects/$projectId/kanban'
import { Route as AppProjectsProjectIdIssuesIssueIdIndexRouteImport } from './routes/app/projects/$projectId/issues/$issueId/index'

const App_routeRoute = App_routeRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => App_routeRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => App_routeRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdMembersRoute =
  AppProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdKanbanRoute =
  AppProjectsProjectIdKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdIndexRoute =
  AppProjectsProjectIdIssuesIssueIdIndexRouteImport.update({
    id: '/issues/$issueId/',
    path: '/issues/$issueId/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof App_routeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/projects/$projectId/kanban': typeof AppProjectsProjectIdKanbanRoute
  '/app/projects/$projectId/members': typeof AppProjectsProjectIdMembersRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/issues/$issueId/': typeof AppProjectsProjectIdIssuesIssueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$projectId/kanban': typeof AppProjectsProjectIdKanbanRoute
  '/app/projects/$projectId/members': typeof AppProjectsProjectIdMembersRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof App_routeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/projects/$projectId/kanban': typeof AppProjectsProjectIdKanbanRoute
  '/app/projects/$projectId/members': typeof AppProjectsProjectIdMembersRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/issues/$issueId/': typeof AppProjectsProjectIdIssuesIssueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/kanban'
    | '/app/projects/$projectId/members'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/issues/$issueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/app/projects/$projectId/kanban'
    | '/app/projects/$projectId/members'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/issues/$issueId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/kanban'
    | '/app/projects/$projectId/members'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/issues/$issueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  App_routeRoute: typeof App_routeRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof App_routeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof App_routeRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof App_routeRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/members': {
      id: '/app/projects/$projectId/members'
      path: '/members'
      fullPath: '/app/projects/$projectId/members'
      preLoaderRoute: typeof AppProjectsProjectIdMembersRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/kanban': {
      id: '/app/projects/$projectId/kanban'
      path: '/kanban'
      fullPath: '/app/projects/$projectId/kanban'
      preLoaderRoute: typeof AppProjectsProjectIdKanbanRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/issues/$issueId/': {
      id: '/app/projects/$projectId/issues/$issueId/'
      path: '/issues/$issueId'
      fullPath: '/app/projects/$projectId/issues/$issueId/'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdKanbanRoute: typeof AppProjectsProjectIdKanbanRoute
  AppProjectsProjectIdMembersRoute: typeof AppProjectsProjectIdMembersRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdIssuesIssueIdIndexRoute: typeof AppProjectsProjectIdIssuesIssueIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdKanbanRoute: AppProjectsProjectIdKanbanRoute,
  AppProjectsProjectIdMembersRoute: AppProjectsProjectIdMembersRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdIssuesIssueIdIndexRoute:
    AppProjectsProjectIdIssuesIssueIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface App_routeRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const App_routeRouteChildren: App_routeRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const App_routeRouteWithChildren = App_routeRoute._addFileChildren(
  App_routeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  App_routeRoute: App_routeRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
